username = "someone@example.com"
password = "SomePassword"

# zone: mandatory string
# has to be exact, as found on the webpage
zone = "<Zone Name>" 

# desk: mandatory string
# wanted desk's number. It accepts 0X and X format too if it's only 1 digit.
desk = "<Desk Name>"

# weekdays: optional list
# books 1 or more weeks ahead for the current day of the week if empty or missing
# weekdays = ["Monday", "Wednesday"]
